### ISSUE TITLE
Preporuke za online ucenje

### ISSUE THREAD

**Issue by arsics** [misaizdaleka/kako-postati-programer#1]
Pozdrav,
imam vrlo pozitivnih iskustava sa početnicima na sajtovima Coursera.org i Udemy.com, bilo bi dobro da se dodaju u tekst. Verujem da ih i sam znaš, ono sto je njihova prednost za početnike je podela po sekcijama sa testovima/projektima na kraju sekcija. Ima dosta besplatnih kurseva, ali treba razmotriti i plaćene kurseve jer su im cene smešne za ono što nude (na popustima se većina može kupiti za 10-20$). Znam da je plaćanje za nešto nematerijalno na netu tabu za Srbe, treba to promeniti.

**Comment by misaizdaleka** [comment]
Upravo sam to zapisao kao podsetnik sebi da ubacim :) Zapravo, hteo sam Nettuts da stavim prvo, da kažem da se plaća i da treba svakako uložiti u tako nešto, tako da se tu slažemo. 

Ubaciću i Coursera i Udemy. Ako si raspoložen, slobodno mi pusti pull-request, pa da zajedno to odradimo.

**Comment by misaizdaleka** [comment]
Ubačeno.
