### ISSUE TITLE
Pohvala :)

### ISSUE THREAD

**Issue by denisjovic** [misaizdaleka/kako-postati-programer#2]
Ja bih samo da se zahvalim na odlicnom tekstu, jednostavno i prakticno, idealno za pocetnike!

**Comment by misaizdaleka** [comment]
Hvala lepo, drago mi je da je od koristi. Ako imaš bilo kakve sugestije, slobodno ih izloži :)

**Comment by denisjovic** [comment]
Za sada nikakve sugestije, samo pohvala. :) Ja sam vise puta pokusavao da
pocnem da ucim programiranje, ali mi je najveci problem bio sto nisam znao
kako i odakle da pocnem i na koji nacin uopste da ucim, a ovaj tekst mi je
dosta pomogao i uz konsultacije sa drugarom koji se time bavi, konacno sam
poceo i nemam nameru da odustanem...

2015-10-09 18:29 GMT+02:00 misaizdaleka notifications@github.com:
