### ISSUE TITLE
Hvala

### ISSUE THREAD

**Issue by JokiNS** [misaizdaleka/kako-postati-programer#3]
Ovde je apsolutno najbolje objašnjen put do rezultata. Bar od onoga na šta sam do sada naletao na internetu. Posebno onaj deo sa WinWin stranicom i Politikom i daljim konkretnim koracima kud dalje. Hvala ti na tim informacijama.

Imam samo jedno pitanje za tebe. Koliko je pametno paralelno sa učenjem pravog web programiranja, pokušavati ućariti neki dinar praveći drugima sajtove u WordPress-u?

**Comment by misaizdaleka** [comment]
Hvala lepo na pohvalama :)

Ako imaš dovoljno slobodnog vremena, što da ne. Ja lično WP uopšte ne volim, jer nije namenjen programerima, već upravo ljudima koji nisu tehnički potkovani. To ne znači da programeri ne mogu da ga koriste, ali čim budeš probao nešto ozbiljnije da isprogramiraš u njemu (mada on toliko plugin-ova ima da će se to verovatno retko dešavati), odmah će ti biti jasno o čemu pričam :)

Ako imaš dovoljno novca za život, ja bih ti savetovao da se fokusiraš isključivo na učenje programiranja. Ukoliko ipak želiš i neki keš da zaradiš što pre, WP može biti dobar izbor, posebno za nekog ko tek ulazi u programerske vode.
