### ISSUE TITLE
Covek iz tvoje price

### ISSUE THREAD

**Issue by DraskoSimic** [misaizdaleka/kako-postati-programer#4]
Druze, pronasao sam se u tvom tekstu i dao mi je odlicne smernice.  Potpuno sam razumeo korake i evo prva dva koraka odradjujem temeljno. Da li preporucijes neku knjigu za pocetnike? Nesto za sam pocetak a da prati ove korake koje si naveo. Hvala puno za ovaj tekst.

**Comment by misaizdaleka** [comment]
Drago mi je da ti je uputstvo pomoglo :)

Ništa od knjiga ne čitam za programiranje, pravo da ti kažem - isključivo koristim internet. 
Sada i na YouTube-u imaš gomilu tutorijala, tako da se sigurno i tu može naći nešto korisno. 

Jednu jedinu knjigu iz ove oblasti sam kupio, ali nije za početnike - Clean Code od Uncle Bob-a.
